ITEMS = [
    "Apple - iPhone 17 Pro Max 256GB - Silver (AT&T)",
    "Apple - iPhone 17 256GB - Sage (AT&T)",
    "Apple - 11-inch iPad A16 chip with Wi-Fi - 128GB - Blue",
    "Apple - 11-inch iPad Pro M5 chip Wi-Fi 256GB with OLED - Space Black",
    "14-inch MacBook Pro - Apple M5 chip with 10-core CPU and 10-core GPU - 16GB Memory - 1TB SSD - Silver",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 256GB SSD - Midnight",
    "Apple - AirPods 4 - White",
    "Apple - AirPods 4 with Active Noise Cancellation - White",
    "14-inch MacBook Pro - Apple M5 chip with 10-core CPU and 10-core GPU - 16GB Memory - 512GB SSD - Space Black",
    "Apple - 240W USB-C Charge Cable (2 m) - White",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 256GB SSD - Midnight",
    "Apple - AirPods 4 - White",
    "Apple - AirPods 4 with Active Noise Cancellation - White",
    "14-inch MacBook Pro - Apple M5 chip with 10-core CPU and 10-core GPU - 16GB Memory - 512GB SSD - Space Black",
    "Apple - 240W USB-C Charge Cable (2 m) - White",
    "Apple - AirPods Max (USB-C) - Midnight",
    "Apple - AirTag (4-Pack) - Silver",
    "Apple - 6.6' (2M) USB-C to MagSafe 3 Charging Cable for MacBook Pro - White",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 512GB SSD - Midnight",
    "14-inch MacBook Pro - Apple M5 chip with 10-core CPU and 10-core GPU - 24GB Memory - 1TB SSD - Space Black",
    "Apple - Magic Mouse - Multi-Touch Surface (USB-C) - Wireless - Black Multi-Touch Surface",
    "Apple - iPhone 15 128GB (Unlocked) - Blue",
    "Apple - iPhone 15 128GB (Unlocked) - Black",
    "Apple - iPhone 15 128GB (Unlocked) - Pink",
    "Apple - Refurbished Excellent - iPhone 15 128GB 6.1 5G Fully Unlocked - Black",
    "Apple - iPhone 16e 128GB - Apple Intelligence (Unlocked) - Black",
    "Apple - iPhone 16e 128GB - Apple Intelligence (Unlocked) - Black",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 256GB SSD - Silver",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 256GB SSD - Sky Blue",
    "Apple - MacBook Air 13-inch Laptop - Apple M4 chip Built for Apple Intelligence - 16GB Memory - 256GB SSD - Starlight",
    "14-inch MacBook Pro - Apple M5 chip with 10-core CPU and 10-core GPU - 16GB Memory - 512GB SSD - Silver",
    "Apple - AirPods Max (USB-C) - Starlight",
    "Apple - AirPods Max (USB-C) - Blue",
    "Apple - AirPods Max (USB-C) - Orange",
    "Apple - AirPods Max (USB-C) - Purple",
    "Package - Apple - MacBook Pro 16-inch Laptop - Apple M4 Max chip Built for Apple Intelligence - 48GB Memory - 1TB SSD - Space Black and Sony - Alpha 7R V Full-frame Mirrorless Camera with Interchangeable Lens (Body Only) - Black",
    "Apple - MacBook Pro 16 Laptop - M3 Max chip Built for Apple Intelligence - 48GB Memory - 40-core GPU - 1TB SSD - Silver - Open Box - Fair",
    "Apple - MacBook Pro 16 Laptop - M3 Max chip Built for Apple Intelligence - 48GB Memory - 40-core GPU - 1TB SSD - Silver - Open Box - Good",
    "Apple - MacBook Pro 16 Laptop - M3 Max chip Built for Apple Intelligence - 48GB Memory - 40-core GPU - 1TB SSD - Silver - Open Box - Excellent",
    "Apple - Geek Squad Certified Refurbished MacBook Pro 16 Laptop - M3 Max chip - 48GB Memory - 40-core GPU - 1TB SSD - Silver",
    "Apple - MacBook Pro 16-inch Laptop - Apple M4 Max chip Built for Apple Intelligence - 48GB Memory - 1TB SSD - Silver",
    "Apple - MacBook Pro 16-inch Laptop - Apple M4 Max chip Built for Apple Intelligence - 48GB Memory - 1TB SSD - Space Black",
    "Apple - Geek Squad Certified Refurbished MacBook Pro 16 Laptop - M3 Max chip - 48GB Memory - 40-core GPU - 1TB SSD - Silver"

    

]

