ITEMS = [
    "Apple - iPhone 15 Pro Max 256GB - Natural Titanium - Unlocked",
    "Apple - iPhone 15 Pro Max 512GB - Natural Titanium - Unlocked",
    "Apple - iPhone 15 Pro 128GB - Blue Titanium - Unlocked",
    "Apple - iPhone 15 Pro 256GB - White Titanium - Unlocked",
    "Apple - iPhone 15 Plus 256GB - Pink - Unlocked",
    "Apple - iPhone 15 128GB - Black - Unlocked",
    "Samsung - Galaxy S24 Ultra 512GB - Titanium Gray - Unlocked",
    "Samsung - Galaxy S24 Ultra 256GB - Titanium Black - Unlocked",
    "Samsung - Galaxy S24 Plus 256GB - Onyx Black - Unlocked",
    "Samsung - Galaxy S24 128GB - Marble Gray - Unlocked",
    "Google - Pixel 8 Pro 256GB - Obsidian - Unlocked",
    "Google - Pixel 8 Pro 128GB - Bay - Unlocked",
    "Google - Pixel 8 128GB - Hazel - Unlocked",
    "Samsung - Galaxy Z Fold5 512GB - Icy Blue - Unlocked",
    "Samsung - Galaxy Z Fold5 256GB - Phantom Black - Unlocked",
    "Samsung - Galaxy Z Flip5 256GB - Lavender - Unlocked",
    "Samsung - Galaxy Z Flip5 128GB - Mint - Unlocked",
    "OnePlus - 12 256GB - Silky Black - Unlocked",
    "Motorola - Edge Plus 256GB - Interstellar Black - Unlocked",
    "Apple - iPhone 14 Pro Max 256GB - Space Black - Unlocked",
    "Apple - MacBook Pro 16 inch Laptop - Apple M3 Max chip - 36GB Memory - 1TB SSD - Space Black",
    "Apple - MacBook Pro 16 inch Laptop - Apple M3 Max chip - 48GB Memory - 2TB SSD - Silver",
    "Apple - MacBook Pro 14 inch Laptop - Apple M3 Pro chip - 18GB Memory - 512GB SSD - Space Black",
    "Apple - MacBook Pro 14 inch Laptop - Apple M3 Pro chip - 36GB Memory - 1TB SSD - Silver",
    "Apple - MacBook Air 15 inch Laptop - Apple M2 chip - 16GB Memory - 512GB SSD - Midnight",
    "Apple - MacBook Air 13 inch Laptop - Apple M2 chip - 8GB Memory - 256GB SSD - Starlight”, ”Dell - XPS 15 Laptop - Intel Core i9 - 32GB Memory - 1TB SSD",
    "Dell - XPS 13 Plus Laptop - Intel Core i7 - 16GB Memory - 512GB SSD",
    "HP - Spectre x360 14 inch 2 in 1 Laptop - Intel Evo i7 - 16GB Memory - 1TB SSD",
    "HP - Envy 16 inch Laptop - Intel Core i7 - 16GB Memory - 1TB SSD",
    "Lenovo - Legion 7 Gaming Laptop - AMD Ryzen 9 - 32GB Memory - RTX 4080",
    "Lenovo - Legion Pro 5 Gaming Laptop - AMD Ryzen 7 - 16GB Memory - RTX 4070",
    "ASUS - ROG Zephyrus G14 Gaming Laptop - AMD Ryzen 9 - 16GB Memory - RTX 4060",
    "ASUS - ROG Strix G16 Gaming Laptop - Intel Core i9 - 32GB Memory - RTX 4080",
    "MSI - Raider GE78 HX Gaming Laptop - Intel Core i9 - 32GB Memory - RTX 4090",
    "Acer - Predator Helios 16 Gaming Laptop - Intel Core i9 - 32GB Memory - RTX 4080",
    "Razer - Blade 18 Gaming Laptop - Intel Core i9 - 32GB Memory - RTX 4090",
    "Microsoft - Surface Laptop Studio 2 - Intel Core i7 - 32GB Memory - 1TB SSD",
    "NVIDIA - GeForce RTX 4090 24GB Graphics Card",
    "NVIDIA - GeForce RTX 4080 Super Graphics Card",
    "NVIDIA - GeForce RTX 4070 Super Graphics Card",
    "NVIDIA - GeForce RTX 4070 Graphics Card",
    "AMD - Radeon RX 7900 XTX Graphics Card",
    "AMD - Radeon RX 7900 XT Graphics Card",
    "AMD - Radeon RX 7800 XT Graphics Card",
    "AMD - Radeon RX 7700 XT Graphics Card",
    "NVIDIA - GeForce RTX 4060 Ti Graphics Card",
    "Intel - Arc A770 Graphics Card",
    "Sony - PlayStation 5 Console - Disc Edition",
    "Sony - PlayStation 5 Console - Digital Edition",
    "Sony - PlayStation 5 Slim Console - Disc Edition",
    "Microsoft - Xbox Series X 1TB Console - Black",
    "Microsoft - Xbox Series S 512GB Console - White",
    "Nintendo - Switch OLED Model - White Joy-Con",
    "Nintendo - Switch OLED Model - Neon Blue and Red Joy-Con",
    "Sony - PlayStation Portal Remote Player",
    "Microsoft - Xbox Elite Wireless Controller Series 2",
    "Sony - DualSense Edge Wireless Controller",
    "Samsung - 77 inch Class S90C OLED 4K UHD Smart Tizen TV",
    "Samsung - 65 inch Class S90C OLED 4K UHD Smart Tizen TV",
    "Samsung - 55 inch Class S90C OLED 4K UHD Smart Tizen TV",
    "LG - 77 inch Class C3 Series OLED evo 4K UHD Smart webOS TV",
    "LG - 65 inch Class C3 Series OLED evo 4K UHD Smart webOS TV",
    "LG - 55 inch Class C3 Series OLED evo 4K UHD Smart webOS TV",
    "Sony - 77 inch Class BRAVIA XR A80L OLED 4K UHD Smart Google TV",
    "Sony - 65 inch Class BRAVIA XR A80L OLED 4K UHD Smart Google TV",
    "TCL - 75 inch Class QM8 Mini-LED QLED 4K UHD Smart Google TV",
    "Hisense - 65 inch Class U8K Mini-LED ULED 4K UHD Smart Google TV"
    "Sony - 55 inch Class BRAVIA XR A80L OLED 4K UHD Smart Google TV",
    "Sony - 65 inch Class X90L LED 4K UHD Smart Google TV",
    "Sony - 75 inch Class X90L LED 4K UHD Smart Google TV",
    "Samsung - 75 inch Class QN90C Neo QLED 4K UHD Smart Tizen TV",
    "Samsung - 65 inch Class QN85C Neo QLED 4K UHD Smart Tizen TV",
    "LG - 75 inch Class QNED85 Mini-LED 4K UHD Smart webOS TV",
    "LG - 65 inch Class QNED80 LED 4K UHD Smart webOS TV",
    "Hisense - 75 inch Class U7K Mini-LED ULED 4K UHD Smart Google TV",
    "TCL - 65 inch Class Q7 QLED 4K UHD Smart Google TV",
    "Insignia - 75 inch Class F50 Series LED 4K UHD Smart Fire TV",
    "Dell - UltraSharp 32 inch 4K USB-C Monitor",
    "Dell - UltraSharp 27 inch 4K USB-C Monitor",
    "LG - UltraGear 27 inch QHD Gaming Monitor",
    "LG - UltraGear 34 inch Ultrawide Gaming Monitor",
    "Samsung - Odyssey Neo G8 32 inch 4K Gaming Monitor",
    "Samsung - Odyssey G9 49 inch Ultrawide Gaming Monitor",
    "ASUS - ROG Swift 27 inch OLED Gaming Monitor",
    "MSI - Optix 27 inch QHD Gaming Monitor",
    "Acer - Nitro 34 inch Ultrawide Gaming Monitor",
    "BenQ - EX2780Q 27 inch QHD Gaming Monitor",
    "Apple - iPad Pro 11 inch Wi-Fi 256GB - Space Black",
    "Apple - iPad Pro 12.9 inch Wi-Fi 512GB - Space Gray",
    "Apple - iPad Air 10.9 inch Wi-Fi 256GB - Blue",
    "Apple - iPad 10th Generation 64GB Wi-Fi - Silver",
    "Apple - iPad mini 6th Generation 256GB Wi-Fi - Purple",
    "Samsung - Galaxy Tab S9 Ultra 512GB Wi-Fi - Graphite",
    "Samsung - Galaxy Tab S9 Plus 256GB Wi-Fi - Beige",
    "Samsung - Galaxy Tab A9 Plus 128GB Wi-Fi - Gray",
    "Microsoft - Surface Pro 9 - Intel Core i7 - 16GB Memory - 512GB SSD",
    "Lenovo - Tab Extreme 256GB OLED Android Tablet",
    "Apple - Apple Watch Ultra 2 GPS Cellular 49mm Titanium Case",
    "Apple - Apple Watch Series 9 GPS 45mm Aluminum Case - Midnight",
    "Apple - Apple Watch Series 9 GPS 41mm Aluminum Case - Starlight",
    "Apple - Apple Watch SE GPS 44mm Aluminum Case - Silver",
    "Samsung - Galaxy Watch6 Classic 47mm Stainless Steel - Black",
    "Samsung - Galaxy Watch6 44mm Aluminum - Graphite",
    "Google - Pixel Watch 2 Wi-Fi - Matte Black Aluminum Case",
    "Garmin - Fenix 7 Multisport GPS Smartwatch - Slate Gray",
    "Garmin - Venu Sq GPS Smartwatch - Shadow Gray",
    "Fitbit - Sense 2 Advanced Health Smartwatch - Lunar White",
    "Apple - AirPods Max USB-C - Midnight",
    "Apple - AirPods Pro 2nd Generation with USB-C Charging Case - White",
    "Apple - AirPods 3rd Generation with Lightning Charging Case - White",
    "Sony - WH-1000XM5 Wireless Noise Canceling Headphones - Black",
    "Bose - QuietComfort Ultra Wireless Noise Canceling Headphones - Black",
    "Sennheiser - Momentum 4 Wireless Noise Canceling Headphones - Black",
    "Beats - Studio Pro Wireless Headphones - Black",
    "JBL - Live Pro 2 True Wireless Earbuds - Black",
    "Samsung - Galaxy Buds2 Pro - Graphite",
    "Nothing - Ear 2 True Wireless Earbuds",
    "Sonos - Arc Soundbar with Dolby Atmos - Black",
    "Sonos - Beam Gen 2 Soundbar with Dolby Atmos - White",
    "Sonos - Sub Mini Wireless Subwoofer - Black",
    "Bose - Smart Soundbar 600 with Dolby Atmos",
    "Samsung - HW-Q990C 11.1.4 Channel Soundbar System",
    "Sony - HT-A7000 Dolby Atmos Soundbar",
    "LG - S95QR 9.1.5 Channel Soundbar System",
    "Vizio - Elevate 5.1.4 Channel Soundbar System",
    "Yamaha - YAS-209 Soundbar with Wireless Subwoofer",
    "Polk Audio - MagniFi Max AX Soundbar",
    "Canon - EOS R8 Mirrorless Camera Body",
    "Canon - EOS R50 Mirrorless Camera with RF-S 18-45mm Lens",
    "Sony - Alpha a6700 Mirrorless Camera Body",
    "Sony - Alpha a6400 Mirrorless Camera with 16-50mm Lens",
    "Sony - ZV-E10 Mirrorless Vlog Camera with 16-50mm Lens",
    "Nikon - Z6 II Mirrorless Camera Body",
    "Nikon - Z30 Mirrorless Camera with 16-50mm Lens",
    "Fujifilm - X-T30 II Mirrorless Camera with 18-55mm Lens",
    "GoPro - HERO12 Black Action Camera",
    "Insta360 - X3 360 Degree Action Camera",
    "DJI - Mini 4 Pro Drone with RC Controller",
    "DJI - Air 3 Drone with RC-N2 Remote Controller",
    "DJI - Mavic 3 Classic Drone",
    "Autel - Evo Lite Plus Drone",
    "Skydio - Mini 2 Plus Drone",
    "Samsung - T7 Shield 4TB External USB 3.2 SSD - Black",
    "Samsung - T7 Shield 2TB External USB 3.2 SSD - Blue",
    "SanDisk - Extreme Pro 4TB External USB-C SSD",
    "Crucial - X9 Pro 2TB Portable SSD",
    "WD - My Passport 5TB External Portable Hard Drive - Black",
    "WD - Black D10 8TB External Gaming Hard Drive",
    "Seagate - FireCuda 530 2TB Internal NVMe SSD",
    "Samsung - 990 Pro 2TB Internal NVMe SSD",
    "Western Digital - SN850X 4TB Internal NVMe SSD",
    "Seagate - Backup Plus Hub 8TB External Desktop Hard Drive",
    "Intel - Core i9-14900K 14th Gen Desktop Processor",
    "Intel - Core i7-14700K 14th Gen Desktop Processor",
    "Intel - Core i5-14600K 14th Gen Desktop Processor",
    "AMD - Ryzen 9 7950X Desktop Processor",
    "AMD - Ryzen 7 7800X3D Desktop Processor",
    "AMD - Ryzen 5 7600X Desktop Processor",
    "Intel - Arc A750 Graphics Card",
    "NVIDIA - GeForce RTX 4060 Graphics Card",
    "AMD - Radeon RX 7600 XT Graphics Card",
    "Intel - Arc A580 Graphics Card",
    "ASUS - RT-AX86U Wi-Fi 6 Router",
    "Netgear - Orbi RBK852 Mesh Wi-Fi System",
    "Eero - Pro 6E Mesh Wi-Fi System",
    "TP-Link - Deco XE75 Mesh Wi-Fi System",
    "Google - Nest Wi-Fi Pro Mesh Router",
    "Linksys - Velop AXE8400 Mesh Wi-Fi System",
    "Ubiquiti - UniFi Dream Router",
    "Arris - SURFboard DOCSIS 3.1 Cable Modem",
    "Motorola - MB8611 DOCSIS 3.1 Cable Modem",
    "Netgear - Nighthawk CM2000 Cable Modem" 
    "Logitech - MX Master 3S Wireless Mouse - Graphite",
    "Logitech - G502 X PLUS Lightspeed Wireless Gaming Mouse",
    "Razer - DeathAdder V3 Pro Wireless Gaming Mouse",
    "SteelSeries - Aerox 3 Wireless Gaming Mouse",
    "Corsair - Dark Core RGB Pro SE Wireless Gaming Mouse",
    "HP - Omen Vector Wireless Gaming Mouse",
    "ASUS - ROG Gladius III Wireless Gaming Mouse",
    "Microsoft - Surface Precision Mouse",
    "Apple - Magic Mouse 2 - White",
    "Apple - Magic Trackpad 2 - Silver",
    "HP - OfficeJet Pro 9025e All-in-One Printer",
    "Canon - PIXMA TS9520 Wireless All-in-One Printer",
    "Epson - EcoTank ET-4850 Wireless All-in-One Printer",
    "Brother - MFC-J995DW Wireless All-in-One Inkjet Printer",
    "Canon - imageCLASS MF445dw Monochrome Laser Printer",
    "Brother - HL-L2350DW Monochrome Laser Printer",
    "Epson - EcoTank ET-2760 Wireless All-in-One Printer",
    "HP - LaserJet Pro M404dw Monochrome Printer",
    "Lexmark - MC3224dwe Color Laser Printer",
    "Samsung - Xpress SL-C430W Color Laser Printer",
    "TP-Link - Kasa Smart Plug Mini",
    "TP-Link - Kasa Smart Wi-Fi Light Switch",
    "TP-Link - Deco M9 Plus Mesh Wi-Fi System",
    "Amazon - Echo Show 8 Smart Display",
    "Amazon - Echo Dot (5th Gen) Smart Speaker",
    "Google - Nest Hub 2nd Gen Smart Display",
    "Google - Nest Mini 2nd Gen Smart Speaker",
    "Wyze - Cam v3 Outdoor/Indoor Smart Camera",
    "Ring - Video Doorbell 4",
    "Ring - Video Doorbell Pro 2",
    "Apple - MagSafe Duo Charger",
    "Apple - 20W USB-C Power Adapter",
    "Apple - 30W USB-C Power Adapter",
    "Apple - 35W Dual USB-C Charger",
    "Apple - 240W USB-C Power Adapter",
    "Samsung - 25W USB-C Fast Charger",
    "Samsung - Wireless Charger Stand",
    "Anker - 65W PowerPort III GaN Charger",
    "Anker - PowerPort Atom III Slim 30W",
    "Belkin - BoostCharge Wireless Charging Stand",
    "DJI - Osmo Mobile 6 Smartphone Gimbal",
    "DJI - Ronin-SC Camera Stabilizer",
    "Zhiyun - Weebill S Gimbal",
    "FeiyuTech - AK4500 3-Axis Gimbal",
    "GoPro - Karma Grip Stabilizer",
    "Garmin - Fenix 7 Multisport GPS Smartwatch - Slate Gray",
    "Garmin - Venu Sq GPS Smartwatch - Shadow Gray",
    "Fitbit - Sense 2 Advanced Health Smartwatch - Lunar White",
    "Fitbit - Versa 4 Health Smartwatch - Black",
    "Samsung - Galaxy Watch6 Classic 47mm Stainless Steel - Black",
    "Samsung - Galaxy Watch6 44mm Aluminum - Graphite",
    "Google - Pixel Watch 2 Wi-Fi - Matte Black Aluminum Case",
    "Amazfit - GTR 4 GPS Smartwatch - Obsidian",
    "Suunto - 9 Peak GPS Smartwatch - All Black",
    "Polar - Grit X Pro GPS Smartwatch - Black",
    "Canon - RF 24-70mm F2.8L IS USM Lens",
    "Canon - RF 50mm F1.2L USM Lens",
    "Sony - FE 24-70mm F2.8 GM Lens",
    "Sony - FE 85mm F1.4 GM Lens",
    "Nikon - Z 24-70mm f/2.8 S Lens",
    "Nikon - Z 50mm f/1.8 S Lens",
    "Sigma - 35mm F1.4 DG HSM Art Lens",
    "Tamron - 28-75mm F2.8 Di III RXD Lens",
    "Fujifilm - XF 16-55mm F2.8 R LM WR Lens",
    "Fujifilm - XF 50mm F1.0 R WR Lens",
    "Roku - Streaming Stick 4K+",
    "Amazon - Fire TV Stick 4K Max",
    "Apple - TV 4K 64GB 3rd Generation",
    "Google - Chromecast with Google TV",
    "NVIDIA - Shield TV Pro Streaming Device",
    "TiVo - Stream 4K Max",
    "Xfinity - Flex Streaming TV Box",
    "Hisense - Roku TV 50 inch",
    "TCL - Roku TV 55 inch",
    "Insignia - Fire TV 50 inch",
    "Philips - Hue White and Color Ambiance Starter Kit",
    "Lutron - Caseta Smart Lighting Dimmer Kit",
    "Ring - Smart Lighting Spotlight Kit",
    "Arlo - Pro 4 Floodlight Camera",
    "Wyze - Smart LED Bulb 2-Pack",
    "Eufy - Security Floodlight Camera 2K",
    "TP-Link - Kasa Smart Light Strip",
    "Nanoleaf - Shapes Hexagon Smarter Kit",
    "GE - C by GE Smart Bulb",
    "Leviton - Decora Smart Wi-Fi Dimmer",
    "NVIDIA - Shield TV Game Streaming Device",
    "Razer - Kishi V2 Mobile Gaming Controller",
    "Microsoft - Xbox Wireless Controller",
    "Sony - DualSense Edge Wireless Controller",
    "Nintendo - Switch Pro Controller",
    "SteelSeries - Nimbus+ Wireless Controller",
    "8BitDo - Pro 2 Wireless Controller",
    "Logitech - G Cloud Handheld Gaming Device",
    "ASUS - ROG Ally Handheld Gaming Device",
    "Acer - Predator Gaming Keyboard Bundle"
]



