ITEMS = [
    "Samsung - 65 inch Class S90C OLED 4K UHD Smart Tizen TV",
    "Samsung - 55 inch Class S90C OLED 4K UHD Smart Tizen TV",
    "LG - 65 inch Class C3 Series OLED evo 4K UHD Smart webOS TV",
    "LG - 55 inch Class C3 Series OLED evo 4K UHD Smart webOS TV",
    "Sony - 65 inch Class BRAVIA XR A80L OLED 4K UHD Smart Google TV",
    "Sony - 55 inch Class BRAVIA XR A80L OLED 4K UHD Smart Google TV",
    "TCL - 75 inch Class QM8 Q-Class Mini-LED QLED 4K UHD Smart Google TV",
    "TCL - 65 inch Class QM8 Q-Class Mini-LED QLED 4K UHD Smart Google TV",
    "Hisense - 65 inch Class U8K Mini-LED ULED 4K UHD Smart Google TV",
    "Hisense - 55 inch Class U7K Mini-LED ULED 4K UHD Smart Google TV",
    "Apple - MacBook Air 13.6 inch Laptop - Apple M2 chip - 8GB Memory - 256GB SSD - Midnight",
    "Apple - MacBook Air 15.3 inch Laptop - Apple M2 chip - 8GB Memory - 256GB SSD - Silver",
    "Apple - MacBook Pro 14 inch Laptop - Apple M3 chip - 16GB Memory - 512GB SSD - Space Black",
    "Apple - MacBook Pro 16 inch Laptop - Apple M3 Pro chip - 18GB Memory - 512GB SSD - Silver",
    "Dell - XPS 13 Plus Laptop - 13.4 inch OLED - Intel Core i7 - 16GB Memory - 512GB SSD",
    "HP - Spectre x360 2-in-1 14 inch Laptop - Intel Evo i7 - 16GB Memory - 1TB SSD",
    "Lenovo - Yoga 9i 2-in-1 14 inch Laptop - Intel Evo i7 - 16GB Memory - 1TB SSD",
    "ASUS - ROG Zephyrus G14 14 inch Gaming Laptop - AMD Ryzen 9 - 16GB Memory - RTX 4060",
    "Acer - Aspire 5 15.6 inch Laptop - Intel Core i5 - 8GB Memory - 512GB SSD",
    "Microsoft - Surface Laptop 5 - 13.5 inch Touch Screen - Intel Core i7 - 16GB Memory",
    "Apple - iPhone 15 Pro Max 256GB - Natural Titanium - Unlocked",
    "Apple - iPhone 15 Pro 128GB - Blue Titanium - Unlocked",
    "Apple - iPhone 15 128GB - Black - Unlocked",
    "Apple - iPhone 15 Plus 256GB - Pink - Unlocked",
    "Samsung - Galaxy S24 Ultra 512GB - Titanium Gray - Unlocked",
    "Samsung - Galaxy S24 Plus 256GB - Onyx Black - Unlocked",
    "Google - Pixel 8 Pro 256GB - Obsidian - Unlocked",
    "Google - Pixel 8 128GB - Hazel - Unlocked",
    "Samsung - Galaxy Z Fold5 512GB - Icy Blue - Unlocked",
    "Samsung - Galaxy Z Flip5 256GB - Lavender - Unlocked",
    "Apple - Apple Watch Series 9 GPS 45mm Aluminum Case - Midnight",
    "Apple - Apple Watch Ultra 2 GPS + Cellular 49mm Titanium Case",
    "Samsung - Galaxy Watch6 Classic 47mm Stainless Steel - Black",
    "Google - Pixel Watch 2 Wi-Fi - Matte Black Aluminum Case",
    "Garmin - Fenix 7 Multisport GPS Smartwatch - Slate Gray",
    "Fitbit - Charge 6 Advanced Fitness and Health Tracker - Black",
    "Sony - PlayStation 5 Console - Disc Edition",
    "Sony - PlayStation 5 Console - Digital Edition",
    "Microsoft - Xbox Series X 1TB Console - Black",
    "Microsoft - Xbox Series S 512GB Console - White",
    "Nintendo - Switch OLED Model - White Joy-Con",
    "Nintendo - Switch Console - Neon Red and Blue Joy-Con",
    "Sony - DualSense Wireless Controller for PlayStation 5 - White",
    "Microsoft - Xbox Wireless Controller - Carbon Black",
    "Nintendo - Switch Pro Controller - Black",
    "Logitech - G Pro X Superlight Wireless Gaming Mouse - Black",
    "SteelSeries - Apex Pro Mechanical Gaming Keyboard",
    "Corsair - K70 RGB Pro Mechanical Gaming Keyboard",
    "Sonos - Arc Soundbar with Dolby Atmos - Black",
    "Sonos - Beam Gen 2 Soundbar with Dolby Atmos - White",
    "Bose - Smart Soundbar 600 with Dolby Atmos",
    "Sony - HT-A7000 7.1.2 Channel Dolby Atmos Soundbar",
    "JBL - Bar 500 5.1 Channel Soundbar with Wireless Subwoofer",
    "Apple - AirPods Pro 2nd Generation with USB-C Charging Case - White",
    "Apple - AirPods 3rd Generation with Lightning Charging Case - White",
    "Sony - WH-1000XM5 Wireless Noise Canceling Headphones - Black",
    "Bose - QuietComfort Ultra Wireless Noise Cancelling Headphones - Black",
    "Sennheiser - Momentum 4 Wireless Noise Cancelling Headphones - Black",
    "Canon - EOS R50 Mirrorless Camera with RF-S 18-45mm Lens",
    "Sony - Alpha a6400 Mirrorless Camera with 16-50mm Lens",
    "Sony - ZV-E10 Mirrorless Vlog Camera with 16-50mm Lens",
    "Nikon - Z30 Mirrorless Camera with 16-50mm Lens",
    "GoPro - HERO12 Black 5.3K Action Camera",
    "DJI - Mini 4 Pro Drone with RC Controller",
    "DJI - Air 3 Drone with RC-N2 Remote Controller",
    "Ring - Video Doorbell Pro 2 - Satin Nickel",
    "Google - Nest Doorbell Battery - Snow",
    "Arlo - Pro 5S 2K Wire-Free Security Camera",
    "Eufy - SoloCam S340 Outdoor Security Camera",
    "Samsung - T7 Shield 2TB External USB 3.2 SSD - Black",
    "SanDisk - Extreme Pro 2TB External USB-C SSD",
    "WD - My Passport 5TB External USB 3.0 Portable Hard Drive - Black",
    "Seagate - Backup Plus Hub 8TB External USB 3.0 Desktop Hard Drive",
    "Dyson - V15 Detect Cordless Vacuum Cleaner - Yellow Nickel",
    "Dyson - V8 Origin Cordless Vacuum - Nickel Blue",
    "iRobot - Roomba j7 Plus Wi-Fi Connected Self-Emptying Robot Vacuum",
    "Roborock - Q8 Max Plus Robot Vacuum with Auto-Empty Dock",
    "Apple - TV 4K 128GB 3rd Generation - Wi-Fi and Ethernet",
    "Roku - Ultra Streaming Media Player - Black",
    "NVIDIA - SHIELD TV Pro 4K HDR Streaming Media Player",
    "Intel - Core i7-14700K 14th Gen Desktop Processor",
    "AMD - Ryzen 7 7800X3D Desktop Processor",
    "NVIDIA - GeForce RTX 4070 SUPER 12GB GDDR6X Graphics Card",
    "AMD - Radeon RX 7800 XT 16GB GDDR6 Graphics Card"
]


